### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by dfszb** [hoehermann/purple-signald#37]
I get and exception in the signald log when logging in:

18:09:00.798 [main] INFO  io.finn.signald.Main - Binding to socket /home/szb/signald/signald.sock
18:09:00.813 [main] INFO  io.finn.signald.Main - Started signald +git2021-02-01r.
18:09:22.129 [socketlistener] INFO  io.finn.signald.SocketHandler - Client connected
18:09:23.217 [socketlistener] INFO  manager-**********97 - Creating new manager for **********97 (stored at ***
18:09:27.425 [socketlistener] ERROR io.finn.signald.SocketHandler - Catching
java.lang.NullPointerException: null
	at io.finn.signald.storage.ProfileCredentialStore.update(ProfileCredentialStore.java:80) ~[signald.jar:unspecified]
	at io.finn.signald.actions.RefreshProfileAction.run(RefreshProfileAction.java:70) ~[signald.jar:unspecified]
	at io.finn.signald.Manager.getRecipientProfileKeyCredential(Manager.java:1564) ~[signald.jar:unspecified]
	at io.finn.signald.Manager.init(Manager.java:294) ~[signald.jar:unspecified]
	at io.finn.signald.Manager.get(Manager.java:157) ~[signald.jar:unspecified]
	at io.finn.signald.Manager.get(Manager.java:144) ~[signald.jar:unspecified]
	at io.finn.signald.Manager.getAll(Manager.java:192) ~[signald.jar:unspecified]
	at io.finn.signald.JsonAccountList.<init>(JsonAccountList.java:27) ~[signald.jar:unspecified]
	at io.finn.signald.SocketHandler.listAccounts(SocketHandler.java:381) ~[signald.jar:unspecified]
	at io.finn.signald.SocketHandler.handleRequest(SocketHandler.java:189) [signald.jar:unspecified]
	at io.finn.signald.SocketHandler.run(SocketHandler.java:134) [signald.jar:unspecified]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by hoehermann** [comment]
This looks like a problem in signald rather than this plug-in. Please open an issue at https://gitlab.com/signald/signald/-/issues.

**Comment by hoehermann** [comment]
@dfszb Does this still happen?

**Comment by hoehermann** [comment]
Closing due to lack of response.
