### ISSUE TITLE
list_contacts leads to NullPointerException in signald

### ISSUE THREAD

**Issue by hoehermann** [hoehermann/purple-signald#62]
[connection-pid-8851] INFO  io.finn.signald.clientprotocol.ClientConnection - Client connected
    [list_contacts] ERROR list_contacts - error while handling request
    java.lang.NullPointerException: null
            at org.whispersystems.libsignal.util.guava.Preconditions.checkNotNull(Preconditions.java:189) ~[signal-client-java-x86_64-unknown-linux-gnu-0.10.0.jar:?]
            at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:33) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_34.jar:?]
            at org.whispersystems.signalservice.api.push.SignalServiceAddress.<init>(SignalServiceAddress.java:46) ~[signal-service-java-x86_64-unknown-linux-gnu-2.15.3_unofficial_34.jar:?]
            at io.finn.signald.clientprotocol.v1.JsonAddress.getSignalServiceAddress(JsonAddress.java:55) ~[signald.jar:?]
            at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:48) ~[signald.jar:?]
            at io.finn.signald.clientprotocol.v1.ListContactsRequest.run(ListContactsRequest.java:33) ~[signald.jar:?]
            at io.finn.signald.clientprotocol.Request.<init>(Request.java:148) [signald.jar:?]
            at io.finn.signald.clientprotocol.ClientConnection$RequestRunner.run(ClientConnection.java:160) [signald.jar:?]
            at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by thefinn93** [comment]
please file this against signald

**Comment by thefinn93** [comment]
Actually, I think I can fix this with just this stack trace. Please try [725d4fd5](https://gitlab.com/signald/signald/-/commit/725d4fd5a03101f1dec5c2aed833005908e3679c)

**Comment by hoehermann** [comment]
Thank you. As libpurple-signald is in pretty bad shape, I was not sure whether it does something wrong or whether it exposes a bug in signald. I just commented out the request in my local copy, experienced https://gitlab.com/signald/signald/-/issues/246 and decided this was a problem for another day. ;)
